<img src= "MSTS_Logo.png" style ="width:400px;height:400px"/>

## Welcome to our Numpy Notebook 
Numpy is a key library in Python, especially when are looking to analyze data. Here is our MSTS Numpy notebook. It's impossible to cover all of Numpy in one notebook, but hopefully this gives you a descent idea of how it works. Make sure you play around with everything on your own to really understand!

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Finance with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

## Using NumPy

Once you've installed NumPy using: 

`pip install numpy`


you can import it as a library:

In [1]:
import numpy as np

## Numpy Important concepts

The most important concepts in Numpy with respect to Finance include

1. Arrays 
2. Matrices

Let us begin with arrays

# Numpy Arrays
Arrays are effectively lists of numbers, sotred in the form of a matrix as you know it from mathematics. When this matrix has 1 column or 1 row, this is known as a 1-d array : aka a vector. When there are multiple rows and/or columns this is known as a nD array, where n is the dimension (e.g 3D array has 3 rows)

In [3]:
# Creating an array
a_list = [1,2,3]
a_list

[1, 2, 3]

In [4]:
#Turn the list into a numpy array
np.array(a_list)

array([1, 2, 3])

In [6]:
#create lists within lists
matrix = [[1,2,3],[1,2,3],[1,2,3]]
matrix

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [8]:
#and them create a matrix using numpy
#This matrix is made up of 3 arrays
np.array(matrix)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [12]:
#Generating a list using the list and range functions 
list(range(0,5))

[0, 1, 2, 3, 4]

In [13]:
#Generate a numpy array directly using arange
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [16]:
#arange takes a start parameter, a stop parameter, and an optional step parameter (default is 1)
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [17]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [18]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [19]:
#zeros and ones arrays
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
#The .zeros methods takes in the array shape as first parameter in the form of an int or a tuple
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [3]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [16]:
#Evenly spacing number
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [21]:
#Identify matrix
#The .eye method gives us an identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
#Matrix from 1 to 8
#Use the .reshape method to reshape your array into a matrix
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
#Notice that you have to make sure the product of m and n (matrix size) 
# is equal to the paramter you pass into the arange method
np.arange(18).reshape(6,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [25]:
np.arange(18).reshape(2,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [26]:
np.arange(18).reshape(3,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [36]:
#Linspace method
#Returns evenly spaced numbers over a specified interval 
#First three parameters are start, stop & the amount of numbers you want in between num
#Remember we start at 0 therefore num parameter may need to be adjusted
np.linspace(0,1,101)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

## Random
As in Python, we can use tha random and rand operator to obtain random series of numbers. This is particularly useful when we execute simulations such as Monte Carlo simulations.

In [46]:
#Create an array with random numbers from 0 to 1
np.random.rand(1)

array([0.77096285])

In [47]:
#Create a 3x3 with random numbers from 0 to 1
np.random.rand(3,3)

array([[0.96706318, 0.54692968, 0.1888992 ],
       [0.13083763, 0.66337347, 0.24081719],
       [0.87652836, 0.68713036, 0.20194549]])

In [48]:
#Get random integers from certain bounds
np.random.randint(1,10)
#tip : run it again and see what happens

3

In [55]:
#Create an array of random integers
#Parameter are low, high & size
np.random.randint(1,10,5)

array([2, 8, 3, 6, 1])

In [56]:
# Reshaping and Sizing
array1 = np.arange(20)
array2 = np.random.randint(0,100,10)

In [57]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [58]:
array2

array([84,  2, 55, 94, 41, 38, 18, 24, 18, 38])

In [26]:
#Note that these number should multiply to the amount of numbers in your original array
array1.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [27]:
array1.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [28]:
#You can't fit 20 data points into a 2 by 3 matrix
array1.reshape(2,3)

ValueError: cannot reshape array of size 20 into shape (2,3)

In [61]:
#Generate numbers form the standard normal distribution
np.random.randn(20)

array([-1.52451355,  1.23324583,  0.78442051,  0.6301059 ,  1.40620255,
       -1.25408315, -1.19066448,  0.56159129,  0.52620312,  0.1281933 ,
       -0.53352066,  0.84266761, -2.02367853, -1.07349883, -0.90283217,
        0.35742713, -1.76343169,  0.17233204,  1.26962883,  1.28420004])

In [62]:
#You can reshape this array however you want
np.random.randn(20).reshape(5,4)

array([[-1.9775341 , -0.72705501,  0.08216481,  0.15301136],
       [-0.13340309,  0.11210136,  0.3076322 , -2.17709007],
       [-0.54698413,  1.19989241,  2.83673306, -1.29412694],
       [-1.58014149,  0.97794653,  1.11601821,  0.95589998],
       [ 3.11379866, -0.07277846,  0.59122541,  0.24841862]])

In [9]:
#Create a 10by10 matrix of all floats up to 1
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [29]:
#Max and min arguments 
array2.max()

97

In [30]:
array2.min()

19

In [63]:
#Argmax and argmin tell us which argument it is that has the max and min value
array2.argmax()

3

In [32]:
array2.argmin()

6

In [34]:
#Note that shape is not a method you call on the array
#Shape is an attribute of the array itself 
#For those familiar with OOP, shape is a field of the array class
array1.shape

(20,)

In [64]:
#Obviously if you shape an array into a matrix, the shape field changes
array1.reshape(5,4).shape

(5, 4)

In [65]:
#Dtype tells you the datatype you array is storing
array2.dtype

dtype('int64')

# Indexing and Selection 
How can we access, separate, select certain elements from the numpy array?

In [67]:
import numpy as np

In [68]:
array = np.arange(0,11)

In [69]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
#Get value at an index
array[2]

2

In [40]:
#Get value in between 2 indices
array[1:5]

array([1, 2, 3, 4])

In [70]:
#Get value from start to an index
array[:5]

array([0, 1, 2, 3, 4])

In [71]:
#Get value from an index to the end
array[5:]

array([ 5,  6,  7,  8,  9, 10])

In [72]:
#Setting part of an array to a new value
array[2:4] = 1
array

array([ 0,  1,  1,  1,  4,  5,  6,  7,  8,  9, 10])

In [73]:
array = np.arange(0,11)

In [74]:
slice_array = array[2:5]

In [75]:
slice_array[:] = 2

In [76]:
array

array([ 0,  1,  2,  2,  2,  5,  6,  7,  8,  9, 10])

In [ ]:
#Why is tha above important?
#Data is not copied, it affects the array
#Even if you created another array from the first one, the first one will be affected

In [77]:
#To counteract this, use .copy()
array_copy = array.copy()

In [78]:
#Indexing
#Accessing indices is easy using array[row][col] or array[row,col]
array_ex = np.array(([1,2,3],[4,5,6],[7,8,9]))
array_ex

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
#Full row
array_ex[1]

array([4, 5, 6])

In [80]:
#Second element of the second row
array_ex[1][1]

5

In [68]:
# Conditional Selection
#This is super key because we are going to be creating columns depending on certain values/thresholds

In [83]:
an_array = np.arange(1,11)

In [85]:
an_array > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [87]:
#You can pass in the a condition as a variable
bool_arr = an_array > 4

In [89]:
#And then get the part of the array you are looking for
an_array[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [91]:
#or
an_array[an_array>4]

array([ 5,  6,  7,  8,  9, 10])

In [92]:
#Examples
matrix = np.arange(1,26).reshape(5,5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [93]:
#To get only the box defined from 12 to 25
#We wans only from the third row and only past the second item of each row
matrix[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [94]:
#To get one number
matrix[0][0]

1

In [97]:
#Get a single column up to a certain row
matrix[:5,1:2]

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

In [96]:
#Or 
matrix[:3,1]

array([ 2,  7, 12])

# Operations
We can use the array formatting in numpy and perform any type of matrix operation

In [98]:
import numpy as np

In [99]:
arr1 = np.arange(0,20)

In [107]:
#Think of any operation you would want to do to each element, you can probably do it :)
arr1+arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [101]:
arr1*arr1

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [102]:
arr1-arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [103]:
arr1/arr1

<ipython-input-103-f958b1cc4b79>:1: RuntimeWarning: invalid value encountered in true_divide
  arr1/arr1


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [104]:
arr1**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744, 3375, 4096, 4913, 5832, 6859])

In [83]:
np.sqrt(arr1**2)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [84]:
np.exp(arr1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [109]:
np.log(arr1)

<ipython-input-109-ee4fb0b16e6c>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr1)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [110]:
matrix = np.arange(1,26).reshape(5,5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [111]:
matrix.sum()

325

In [112]:
matrix.transpose()

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [113]:
#Make sure to hit tab after you type the dot following an array object to see what you can do to it

In [ ]:
#Quick note
#Using a range and starting at 1, your sum to 25 should be (25*26)/2 = 325

In [24]:
matrix.std()

7.211102550927978

In [28]:
#Sum up by cols
matrix.sum(axis = 0)

array([55, 60, 65, 70, 75])

In [29]:
#Sum up by rows
matrix.sum(axis = 1)

array([ 15,  40,  65,  90, 115])

In [ ]:
### See 